---
project_name: go-snapraid
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/go-snapraid/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}
      - -X main.Commit={{ .FullCommit }}
