name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: "0.37.0"

      - name: Build with TinyGo for ${{ matrix.arch }}
        run: |
          mkdir -p build
          GOARCH=${{ matrix.arch }} \
          GOFLAGS=-buildvcs=false \
          tinygo build \
            -target=linux \
            -no-debug \
            -o build/go-snapraid-linux-${{ matrix.arch }} \
            ./cmd/go-snapraid/main.go

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: go-snapraid-linux-${{ matrix.arch }}
          path: build/go-snapraid-linux-${{ matrix.arch }}
